#todo
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      
  instance:
    hostname: localhost
    prefer-ip-address: true
    

        
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
      
  endpoints:
    web:
      exposure:
        include:
        - "*"
        
 info:
   build:
      artifactId:'@project.artifact@'
      groupId:'@project.groupId@'
      version:'@project.version@'
   java:
      version:'@java.version@'
   author:
      name: 'Vishwa'
      version: '2.0'
                 
